# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      NODE_ENV: development
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
      - run: yarn cache clean
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  prettier:
    environment:
      NODE_ENV: development
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Test that prettier is correct
          command: '/home/circleci/repo/node_modules/.bin/prettier --list-different "*.js"'
  test:
    environment:
      NODE_ENV: development
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run:
          name: Test
          command: '/home/circleci/repo/node_modules/.bin/ava'
workflows:
  version: 2
  build_prettier_test: 
    jobs:
      - build
      - prettier:
          requires:
            - build
      - test:
          requires:
            - build